# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Prototype-Login' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'KakaoSDKCommon'	#필수요소 공통모듈
pod 'KakaoSDKAuth'	#카카오로그인

  # Pods for Prototype-Login

end
